server:
  port: 8081
spring:
  cloud: 
   gateway: 
    routes:
      - id: eventos
        uri: lb://eventos/
        predicates:
          - Path=/eventos/**
      - id: compra
        uri: lb://compra/
        predicates:
          - Path=/cart/**        
